import { Link } from 'react-router-dom';

const features = [
  {
    title: 'AI-Powered Questions',
    desc: 'Get realistic, role-specific interview questions that adapt to your answers in real time.',
  },
  {
    title: 'Instant Feedback',
    desc: 'Receive a detailed score, strengths, and improvement areas the moment you finish.',
  },
  {
    title: 'Track Your Progress',
    desc: 'Review every past interview and watch your average score improve over time.',
  },
];

const steps = [
  { n: '01', title: 'Choose Your Setup', desc: 'Pick a company, role, and difficulty level.' },
  { n: '02', title: 'Answer Questions', desc: 'Respond to AI-generated questions, one at a time.' },
  { n: '03', title: 'Get Your Report', desc: 'Receive a full breakdown of your performance.' },
];

const testimonials = [
  {
    quote: 'Practicing on AstraVox before my placement interviews made a real difference in my confidence.',
    name: 'Priya S.',
    role: 'Final Year, CSE',
  },
  {
    quote: 'The feedback felt genuinely specific, not generic. It pointed out exactly what to improve.',
    name: 'Arjun M.',
    role: 'Final Year, IT',
  },
  {
    quote: 'Being able to review my past answers helped me see patterns in my weak spots.',
    name: 'Sneha R.',
    role: '3rd Year, ECE',
  },
];

const faqs = [
  {
    q: 'Is AstraVox free to use?',
    a: 'Yes, AstraVox is free to use for practicing mock interviews.',
  },
  {
    q: 'How realistic are the interview questions?',
    a: 'Questions are generated by AI based on your chosen company, role, and difficulty, and adapt based on your previous answers.',
  },
  {
    q: 'Can I review my past interviews?',
    a: 'Yes, every completed interview is saved to your history with full questions, answers, and feedback.',
  },
];

const Landing = () => {
  return (
    <div className="bg-slate-950 min-h-screen scroll-smooth">
      <header className="sticky top-0 z-50 backdrop-blur-md bg-slate-950/80 border-b border-slate-800">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <span className="text-xl font-bold text-white">
            Astra<span className="text-cyan-400">Vox</span>
          </span>
          <div className="flex items-center gap-4">
            <Link to="/login" className="text-sm text-slate-300 hover:text-white transition">
              Log in
            </Link>
            <Link
              to="/signup"
              className="text-sm px-4 py-2 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-semibold transition"
            >
              Get Started
            </Link>
          </div>
        </div>
      </header>

      <section className="max-w-4xl mx-auto px-6 pt-28 pb-24 text-center">
        <h1 className="text-5xl md:text-6xl font-bold text-white tracking-tight leading-tight">
          Walk into your next interview
          <br />
          <span className="text-cyan-400">already prepared.</span>
        </h1>
        <p className="text-slate-400 text-lg mt-6 max-w-xl mx-auto">
          Practice realistic, AI-driven mock interviews tailored to any company and role —
          and get honest feedback on exactly what to improve.
        </p>
        <div className="flex items-center justify-center gap-4 mt-10">
          <Link
            to="/signup"
            className="px-6 py-3 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-semibold transition"
          >
            Start Practicing
          </Link>
          
            
        </div>
      </section>

      <section id="how-it-works" className="max-w-5xl mx-auto px-6 py-24 border-t border-slate-900">
        <h2 className="text-3xl font-semibold text-white text-center mb-16">How AstraVox Works</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {steps.map((step) => (
            <div key={step.n}>
              <p className="text-cyan-400 text-sm font-mono mb-3">{step.n}</p>
              <h3 className="text-white font-medium mb-2">{step.title}</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{step.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-5xl mx-auto px-6 py-24 border-t border-slate-900">
        <h2 className="text-3xl font-semibold text-white text-center mb-16">Why Students Choose AstraVox</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {features.map((f) => (
            <div
              key={f.title}
              className="bg-slate-900 border border-slate-800 hover:border-slate-700 rounded-xl p-6 transition hover:-translate-y-1"
            >
              <h3 className="text-white font-medium mb-2">{f.title}</h3>
              <p className="text-slate-400 text-sm leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-5xl mx-auto px-6 py-24 border-t border-slate-900">
        <h2 className="text-3xl font-semibold text-white text-center mb-16">What Students Say</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {testimonials.map((t) => (
            <div key={t.name} className="bg-slate-900 border border-slate-800 rounded-xl p-6">
              <p className="text-slate-300 text-sm leading-relaxed mb-4">&ldquo;{t.quote}&rdquo;</p>
              <p className="text-white text-sm font-medium">{t.name}</p>
              <p className="text-slate-500 text-xs">{t.role}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-3xl mx-auto px-6 py-24 border-t border-slate-900">
        <h2 className="text-3xl font-semibold text-white text-center mb-16">Frequently Asked Questions</h2>
        <div className="space-y-4">
          {faqs.map((faq) => (
            <details
              key={faq.q}
              className="group bg-slate-900 border border-slate-800 rounded-xl p-5"
            >
              <summary className="text-white text-sm font-medium cursor-pointer list-none flex items-center justify-between">
                {faq.q}
                <span className="text-slate-500 group-open:rotate-45 transition-transform">+</span>
              </summary>
              <p className="text-slate-400 text-sm leading-relaxed mt-3">{faq.a}</p>
            </details>
          ))}
        </div>
      </section>

      <footer className="border-t border-slate-900 py-10">
        <div className="max-w-6xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <span className="text-white font-bold">
            Astra<span className="text-cyan-400">Vox</span>
          </span>
          <p className="text-slate-500 text-sm">© 2026 AstraVox. Built for students preparing to succeed.</p>
        </div>
      </footer>
    </div>
  );
};

export default Landing;